name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Tests
        with:
          node-version: '13.x'
        run: |
          npm install
          npm test
